# Generated by Django 4.2.11 on 2024-11-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.CharField(choices=[('a', 'Room A'), ('b', 'Room B')], default='a', max_length=100, verbose_name='Room'),
            preserve_default=False,
        ),
    ]
