# Generated by Django 4.2.11 on 2024-11-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_rename_resource_id_event_resourceid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='resourceId',
            new_name='resource_id',
        ),
    ]
